from templates.legalNotice import LegalNoticeTemplateDocument, LegalNoticeTemplateForm
from templates.Superdari import SuperdariTemplateDocument, SuperdariTemplateForm
from templates.legalCertificate import legalCertificateTemplateDocument , legalCertificateTemplateForm
from templates.PowerofAttorny import PowerOfAttornyTemplateDocument , PowerOfAttornyTemplateForm
from templates.EarlyHearingApplication import EarlyHearingAplicationDocument , EarlyHearingAplicationForm
from templates.DissolusionOfMarriage import DissolutionOfMarriageDocument , DissolutionOfMarriageForm
from templates.Template_strings import *
from templates.PreArrestBailApplication import PreArrestBailApplicationDocument , PreArrestBailApplicationForm
from templates.PreArrestBailCertificate import PreArrestBailCertificateDocument , PreArrestBailCertificateForm
from templates.SuitForSpecificPerformance import SuitForSpecificPerformanceDocument , SuitForSpecificPerformanceForm